/*
|--------------------------------------------|
         ⚡️ Generated by Agentsmith ⚡️
      ⚠️ Do not edit this file directly ⚠️
|--------------------------------------------|
*/
export type Agency = {
    prompts: {
        'compare-input-output': {
            uuid: '013b8568-2872-4eee-9a9a-56fbb3d4f613';
            name: 'Compare input-output';
            slug: 'compare-input-output';
            versions: {
                latest: never;
                '0.0.1': { uuid: 'e0ebd8e6-d58d-4347-9563-e008e06274c5'; version: '0.0.1'; config: { "models": ["arcee-ai/arcee-blitz"], "temperature": 1 }; content: string; variables: { input: string; output: string } }
            }
        };
        'identify-yourself': {
            uuid: 'f9818e00-0957-4b44-8472-0f57a58765e1';
            name: 'Identify Yourself';
            slug: 'identify-yourself';
            versions: {
                latest: never;
                '0.0.1': { uuid: '20bb47d1-e161-471e-a7ec-1f669496f9ba'; version: '0.0.1'; config: { "models": ["openrouter/auto"], "temperature": 1 }; content: string }
            }
        }
    };
    globals: {}
};
