/*
|--------------------------------------------|
         ⚡️ Generated by Agentsmith ⚡️
      ⚠️ Do not edit this file directly ⚠️
|--------------------------------------------|
*/
export type PromptVariables__color_emoji__0_0_1 = {
  color: string;
};
export type PromptVariables__compare_input_output__0_0_1 = {
  input: string;
  output: string;
};
export type PromptVariables__identify_yourself__0_1_3 = {
  showLink: boolean;
};
export type PromptVariables__identify_yourself__0_1_2 = {
  showLink: boolean;
};
export type PromptVariables__identify_yourself__0_1_1 = never;
export type PromptVariables__identify_yourself__0_1_0 = {
  firstName: string;
  lastName: string;
};
export type PromptVariables__identify_yourself__0_0_1 = {
  name: string;
};
export type PromptVariables__support_chat__0_0_2 = {
  userMessage: string;
};
export type PromptVariables__support_chat__0_0_1 = {
  userMessage: string;
};
export type PromptConfig__color_emoji__0_0_1 = {
  models: ['openrouter/auto'];
  temperature: number;
};
export type PromptVersion__color_emoji__0_0_1 = {
  version: '0.0.1';
  config: PromptConfig__color_emoji__0_0_1;
  variables: PromptVariables__color_emoji__0_0_1;
  content: string;
};
export type Prompt__color_emoji = {
  name: 'Color Emoji';
  slug: 'color-emoji';
  versions: {
    latest: PromptVersion__color_emoji__0_0_1;
    '0.0.1': PromptVersion__color_emoji__0_0_1;
  };
};
export type PromptConfig__compare_input_output__0_0_1 = {
  models: ['arcee-ai/arcee-blitz'];
  stream: true;
  temperature: number;
};
export type PromptVersion__compare_input_output__0_0_1 = {
  version: '0.0.1';
  config: PromptConfig__compare_input_output__0_0_1;
  variables: PromptVariables__compare_input_output__0_0_1;
  content: string;
};
export type Prompt__compare_input_output = {
  name: 'Compare input-output';
  slug: 'compare-input-output';
  versions: {
    latest: never;
    '0.0.1': PromptVersion__compare_input_output__0_0_1;
  };
};
export type PromptConfig__identify_yourself__0_1_3 = {
  models: ['mistralai/ministral-3b'];
  temperature: number;
};
export type PromptVersion__identify_yourself__0_1_3 = {
  version: '0.1.3';
  config: PromptConfig__identify_yourself__0_1_3;
  variables: PromptVariables__identify_yourself__0_1_3 & PromptVariables__color_emoji__0_0_1;
  content: string;
};
export type PromptConfig__identify_yourself__0_1_2 = {
  models: ['cohere/command-r'];
  temperature: number;
};
export type PromptVersion__identify_yourself__0_1_2 = {
  version: '0.1.2';
  config: PromptConfig__identify_yourself__0_1_2;
  variables: PromptVariables__identify_yourself__0_1_2;
  content: string;
};
export type PromptConfig__identify_yourself__0_1_1 = {
  models: ['moonshotai/kimi-k2'];
  temperature: number;
};
export type PromptVersion__identify_yourself__0_1_1 = {
  version: '0.1.1';
  config: PromptConfig__identify_yourself__0_1_1;
  variables: PromptVariables__identify_yourself__0_1_1;
  content: string;
};
export type PromptConfig__identify_yourself__0_1_0 = {
  models: ['openrouter/auto'];
  temperature: number;
};
export type PromptVersion__identify_yourself__0_1_0 = {
  version: '0.1.0';
  config: PromptConfig__identify_yourself__0_1_0;
  variables: PromptVariables__identify_yourself__0_1_0;
  content: string;
};
export type PromptConfig__identify_yourself__0_0_1 = {
  models: ['openrouter/auto'];
  temperature: number;
};
export type PromptVersion__identify_yourself__0_0_1 = {
  version: '0.0.1';
  config: PromptConfig__identify_yourself__0_0_1;
  variables: PromptVariables__identify_yourself__0_0_1;
  content: string;
};
export type Prompt__identify_yourself = {
  name: 'Identify Yourself';
  slug: 'identify-yourself';
  versions: {
    latest: PromptVersion__identify_yourself__0_1_1;
    '0.1.3': PromptVersion__identify_yourself__0_1_3;
    '0.1.2': PromptVersion__identify_yourself__0_1_2;
    '0.1.1': PromptVersion__identify_yourself__0_1_1;
    '0.1.0': PromptVersion__identify_yourself__0_1_0;
    '0.0.1': PromptVersion__identify_yourself__0_0_1;
  };
};
export type PromptConfig__support_chat__0_0_2 = {
  models: ['openrouter/auto'];
  stream: true;
  temperature: number;
};
export type PromptVersion__support_chat__0_0_2 = {
  version: '0.0.2';
  config: PromptConfig__support_chat__0_0_2;
  variables: PromptVariables__support_chat__0_0_2;
  content: string;
};
export type PromptConfig__support_chat__0_0_1 = {
  models: ['openrouter/auto'];
  temperature: number;
};
export type PromptVersion__support_chat__0_0_1 = {
  version: '0.0.1';
  config: PromptConfig__support_chat__0_0_1;
  variables: PromptVariables__support_chat__0_0_1;
  content: string;
};
export type Prompt__support_chat = {
  name: 'Support Chat';
  slug: 'support-chat';
  versions: {
    latest: PromptVersion__support_chat__0_0_1;
    '0.0.2': PromptVersion__support_chat__0_0_2;
    '0.0.1': PromptVersion__support_chat__0_0_1;
  };
};
export type Globals = {
  gitHubUrl: 'https://github.com/chad-syntax/agentsmith';
  supportUrl: 'https://agentsmith.dev/support';
  companyName: 'Agentsmith';
  supportEmail: 'support@agentsmith.app';
};
export type Agency = {
  prompts: {
    'color-emoji': Prompt__color_emoji;
    'compare-input-output': Prompt__compare_input_output;
    'identify-yourself': Prompt__identify_yourself;
    'support-chat': Prompt__support_chat;
  };
  globals: Globals;
};
